env:
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io
jobs:
  build-docker:
    env:
      IMAGE_NAME: ${{ github.repository }}
      REGISTRY: ghcr.io
    name: 'Build Docker image: ${{ matrix.alias }}'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.5.0
    - continue-on-error: true
      id: meta
      name: Extract metadata (tags, labels) for Docker
      uses: docker/metadata-action@v3.3.0
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - continue-on-error: true
      name: Build Docker image
      uses: docker/build-push-action@v2.6.1
      with:
        file: ${{ matrix.dockerfile }}
        labels: ${{ steps.meta.outputs.labels }}
        push: false
        tags: ${{ matrix.tags }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - alias: jre-11
          dockerfile: packaging/docker/unix/eclipse-temurin-11-jre/Dockerfile
          tags: test
        - alias: jre-11-alpine
          dockerfile: packaging/docker/unix/eclipse-temurin-11-jre-alpine/Dockerfile
          tags: test-alpine
  build-maven:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B package
      working-directory: .
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: 'Deploy Docker Image: ${{ matrix.alias }}'
    needs:
    - build-maven
    - build-docker
    permissions:
      contents: read
      packages: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Log in to the Container registry
      uses: docker/login-action@v1.10.0
      with:
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
    - continue-on-error: true
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.5.0
    - continue-on-error: true
      id: meta
      name: Extract metadata (tags, labels) for Docker
      uses: docker/metadata-action@v3.3.0
      with:
        flavor: 'latest=${{ matrix.tag-latest }}

          prefix=${{ matrix.tag-prefix }}

          suffix=

          '
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - continue-on-error: true
      name: Build and Deploy Docker image
      uses: docker/build-push-action@v2.6.1
      with:
        context: .
        file: ${{ matrix.dockerfile }}
        labels: ${{ steps.meta.outputs.labels }}
        push: false
        tags: ${{ steps.meta.outputs.tags }} ${{ matrix.extra-tags }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - alias: jre-11
          dockerfile: packaging/docker/unix/eclipse-temurin-11-jre/Dockerfile
          extra-tags: ', ghcr.io/${{ github.repository }}:jre-11'
          tag-latest: true
          tag-prefix: eclipse-temurin-11-jre-
        - alias: jre-11-alpine
          dockerfile: packaging/docker/unix/eclipse-temurin-11-jre-alpine/Dockerfile
          extra-tags: ', ghcr.io/${{ github.repository }}:alpine, ghcr.io/${{ github.repository
            }}:jre-11-alpine'
          tag-latest: false
          tag-prefix: eclipse-temurin-11-jre-alpine-
name: Continuous Delivery
on:
  repository_dispatch:
    types: trigger-ga___docker-cd.yml
