env:
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io
jobs:
  gh-registry-images:
    name: 'Deploy Docker Image: ${{ matrix.alias }}'
    permissions:
      contents: read
      packages: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Determine version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - continue-on-error: true
      name: Set extra tags
      run: echo "RELEASE_EXTRA_TAGS=${{ matrix.extra-tags }}" >> $GITHUB_ENV
    - continue-on-error: true
      name: Log in to the Container registry
      uses: docker/login-action@v1.10.0
      with:
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
    - continue-on-error: true
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.5.0
    - continue-on-error: true
      id: meta
      name: Extract metadata (tags, labels) for Docker
      uses: docker/metadata-action@v3.3.0
      with:
        flavor: 'latest=false

          prefix=${{ matrix.tag-prefix }}

          suffix=

          '
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - continue-on-error: true
      name: Build and Deploy Docker image
      uses: docker/build-push-action@v2.6.1
      with:
        context: .
        file: ${{ matrix.dockerfile }}
        labels: ${{ steps.meta.outputs.labels }}
        push: false
        tags: ${{ steps.meta.outputs.tags }} ${{ env.RELEASE_EXTRA_TAGS }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - alias: jre-11
          dockerfile: packaging/docker/unix/eclipse-temurin-11-jre/Dockerfile
          extra-tags--pattern: ', ghcr.io/${{ github.repository }}:jre-11-$RELEASE_VERSION'
          tag-prefix: eclipse-temurin-11-jre-
        - alias: jre-11-alpine
          dockerfile: packaging/docker/unix/eclipse-temurin-11-jre-alpine/Dockerfile
          extra-tags-pattern: ', ghcr.io/${{ github.repository }}:alpine-$RELEASE_VERSION,
            ghcr.io/${{ github.repository }}:jre-11-alpine-$RELEASE_VERSION'
          tag-prefix: eclipse-temurin-11-jre-alpine-
  gh-release_artifacts:
    name: Publish Artifacts to GitHub Releases
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      id: set-version
      name: Set version
      run: 'version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

        echo "project-version=$version" >> $GITHUB_OUTPUT

        echo "PROJECT_VERSION=$version" >> $GITHUB_ENV

        '
    - continue-on-error: true
      run: echo $PROJECT_VERSION
    - continue-on-error: true
      id: fetch-artifact
      name: Fetch artifact
      run: "GROUP_ID=io/jenkins/jenkinsfile-runner\nARTIFACT_ID=jenkinsfile-runner\n\
        FILE_NAME=jenkinsfile-runner\nPROJECT_VERSION=${{ steps.set-version.outputs.project-version\
        \ }}\necho \"file-name=$FILE_NAME\" >> $GITHUB_OUTPUT\nwget -q https://repo.jenkins-ci.org/releases/$GROUP_ID/$ARTIFACT_ID/$PROJECT_VERSION/$ARTIFACT_ID-$PROJECT_VERSION.zip\
        \ \\\n  -O $FILE_NAME-$PROJECT_VERSION.zip\n"
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: upload-artifact-minimum-package
      name: Upload artifact minimum package
      uses: actions/upload-release-asset@v1.0.2
      with:
        asset_content_type: application/zip
        asset_name: ${{ steps.fetch-artifact.outputs.file-name }}-${{ steps.set-version.outputs.project-version
          }}.zip
        asset_path: ./${{ steps.fetch-artifact.outputs.file-name }}-${{ steps.set-version.outputs.project-version
          }}.zip
        upload_url: ${{ github.event.release.upload_url }}
name: Publish Release Artifacts
on:
  repository_dispatch:
    types: trigger-ga___publish-release-artifact.yml
